[versions]
junit = "5.12.2"
paper = "1.21.4-R0.1-SNAPSHOT"
sqlite = "3.45.3.0"
mythic = "5.6.1"
crucible = "2.0.0"

[libraries]
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
paper-api = { module = "io.papermc.paper:paper-api", version.ref = "paper" }
sqlite-jdbc = { module = "org.xerial:sqlite-jdbc", version.ref = "sqlite" }
mythic-dist = { module = "io.lumine:Mythic-Dist", version.ref = "mythic" }
mythic-crucible = { module = "io.lumine:MythicCrucible-API", version.ref = "crucible" }
